# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraSrv.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43\x61meraSrv.proto\x12\tCameraSrv\"!\n\rCameraRequest\x12\x10\n\x08settings\x18\x01 \x01(\t\"A\n\x0e\x43\x61meraResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\r\n\x05\x61lias\x18\x03 \x01(\t2T\n\tCameraSrv\x12G\n\x10TryTriggerCamera\x12\x18.CameraSrv.CameraRequest\x1a\x19.CameraSrv.CameraResponseB\x14\xaa\x02\x11HAL.MechMind.gRPCb\x06proto3')

_CAMERAREQUEST = DESCRIPTOR.message_types_by_name['CameraRequest']
_CAMERARESPONSE = DESCRIPTOR.message_types_by_name['CameraResponse']

CameraRequest = _reflection.GeneratedProtocolMessageType('CameraRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAREQUEST,
  '__module__' : 'RegionDetectionSrv_pb2'
})

CameraResponse = _reflection.GeneratedProtocolMessageType('CameraResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAMERARESPONSE,
  '__module__' : 'RegionDetectionSrv_pb2'
})

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CameraSrv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021HAL.MechMind.gRPC'
  _globals['_CAMERAREQUEST']._serialized_start=30
  _globals['_CAMERAREQUEST']._serialized_end=63
  _globals['_CAMERARESPONSE']._serialized_start=65
  _globals['_CAMERARESPONSE']._serialized_end=130
  _globals['_CAMERASRV']._serialized_start=132
  _globals['_CAMERASRV']._serialized_end=216
# @@protoc_insertion_point(module_scope)
