# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CameraSrv_pb2 as CameraSrv__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in CameraSrv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CameraSrvStub(object):
    """Camera Service definitions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TryTriggerCamera = channel.unary_unary(
                '/CameraSrv.CameraSrv/TryTriggerCamera',
                request_serializer=CameraSrv__pb2.CameraRequest.SerializeToString,
                response_deserializer=CameraSrv__pb2.CameraResponse.FromString,
                _registered_method=True)


class CameraSrvServicer(object):
    """Camera Service definitions.
    """

    def TryTriggerCamera(self, request, context):
        """Calls out to an external software which will return the camera data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TryTriggerCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.TryTriggerCamera,
                    request_deserializer=CameraSrv__pb2.CameraRequest.FromString,
                    response_serializer=CameraSrv__pb2.CameraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CameraSrv.CameraSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CameraSrv(object):
    """Camera Service definitions.
    """

    @staticmethod
    def TryTriggerCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CameraSrv.CameraSrv/TryTriggerCamera',
            CameraSrv__pb2.CameraRequest.SerializeToString,
            CameraSrv__pb2.CameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
